import {
  Settings,
  FolderPlus,
  Camera,
  GitBranch,
  Search,
  Cloud,
  FileText,
  Archive,
  RotateCcw,
  Tag,
  Zap,
  EyeOff,
  BookOpen,
  Github,
  Terminal,
  Copy,
  Check,
  Database,
  Table,
  Filter,
  ArrowUpDown,
  Users,
  Lock,
  Layers,
  FileJson,
  Braces,
  ListFilter,
  Gauge,
  RefreshCw,
  Link,
  PenTool,
  Trash2,
  Plus,
  ArrowLeft,
  Home,
  ChevronRight,
  Sparkles,
  Code,
  Box,
  Server,
  Container,
  Play,
  Square,
  Network,
  HardDrive,
  Clock,
  Key,
  Hash,
  List,
  FileCode,
  Cpu,
  Activity,
  FolderOpen,
  Download,
  Upload,
  Globe,
  Shield,
  Workflow,
  CircleDot,
  Timer,
  MessageSquare,
  Radio,
  Combine,
  SortAsc,
  BarChart3,
  Infinity,
  Blocks,
  XCircle,
  Menu,
  X,
  LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  settings: Settings,
  "folder-plus": FolderPlus,
  camera: Camera,
  "git-branch": GitBranch,
  search: Search,
  cloud: Cloud,
  "file-text": FileText,
  archive: Archive,
  "rotate-ccw": RotateCcw,
  tag: Tag,
  zap: Zap,
  "eye-off": EyeOff,
  "book-open": BookOpen,
  github: Github,
  terminal: Terminal,
  copy: Copy,
  check: Check,
  database: Database,
  table: Table,
  filter: Filter,
  "arrow-up-down": ArrowUpDown,
  users: Users,
  lock: Lock,
  layers: Layers,
  "file-json": FileJson,
  braces: Braces,
  "list-filter": ListFilter,
  gauge: Gauge,
  "refresh-cw": RefreshCw,
  link: Link,
  "pen-tool": PenTool,
  trash: Trash2,
  plus: Plus,
  "arrow-left": ArrowLeft,
  home: Home,
  "chevron-right": ChevronRight,
  sparkles: Sparkles,
  code: Code,
  box: Box,
  server: Server,
  container: Container,
  play: Play,
  square: Square,
  network: Network,
  "hard-drive": HardDrive,
  clock: Clock,
  key: Key,
  hash: Hash,
  list: List,
  "file-code": FileCode,
  cpu: Cpu,
  activity: Activity,
  "folder-open": FolderOpen,
  download: Download,
  upload: Upload,
  globe: Globe,
  shield: Shield,
  workflow: Workflow,
  "circle-dot": CircleDot,
  timer: Timer,
  "message-square": MessageSquare,
  radio: Radio,
  combine: Combine,
  "sort-asc": SortAsc,
  "bar-chart": BarChart3,
  infinity: Infinity,
  blocks: Blocks,
  "x-circle": XCircle,
  menu: Menu,
  x: X,
};

interface IconProps {
  name: string;
  className?: string;
}

export const Icon = ({ name, className = "" }: IconProps) => {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    return null;
  }

  return <IconComponent className={className} />;
};

export default Icon;
